# Build LyricsMiniplayer.exe with PyInstaller (windowed, no console),
# pack a redistributable zip, and emit release verification artifacts.
$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot

$Version = "1.2.0"
$ReleaseName = "LyricsMiniplayer-v$Version"
$Python = ".\.venv\Scripts\python.exe"

if (-not (Test-Path $Python)) {
    Write-Error "Create and activate a venv first (python -m venv .venv)."
}

function Write-Utf8NoBomFile {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Content
    )
    $encoding = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($Path, $Content, $encoding)
}

Write-Host "==> Installing locked dependencies (require hashes)"
& $Python -m pip install --require-hashes -r requirements.txt
if ($LASTEXITCODE -ne 0) {
    Write-Error "pip install from hashed requirements.txt failed."
}

Write-Host "==> Building executable"
& $Python -m PyInstaller `
    --noconfirm `
    --clean `
    --windowed `
    --onefile `
    --name LyricsMiniplayer `
    --collect-all customtkinter `
    --collect-all winrt `
    --hidden-import winrt.windows.media.control `
    --hidden-import winrt.windows.storage.streams `
    --hidden-import winrt.windows.foundation `
    --hidden-import winrt.windows.foundation.collections `
    --hidden-import PIL._tkinter_finder `
    main.py
if ($LASTEXITCODE -ne 0) {
    Write-Error "PyInstaller failed."
}

if (-not (Test-Path .\dist\LyricsMiniplayer.exe)) {
    Write-Error "Build failed: dist\LyricsMiniplayer.exe not found."
}

$stage = Join-Path $PSScriptRoot "dist\$ReleaseName"
if (Test-Path $stage) {
    Remove-Item $stage -Recurse -Force
}
New-Item -ItemType Directory -Path $stage | Out-Null
Copy-Item .\dist\LyricsMiniplayer.exe $stage
Copy-Item .\packaging\README.txt $stage
Copy-Item .\LICENSE $stage

$zipPath = Join-Path $PSScriptRoot "dist\$ReleaseName.zip"
if (Test-Path $zipPath) {
    Remove-Item $zipPath -Force
}
Compress-Archive -Path (Join-Path $stage "*") -DestinationPath $zipPath

# --- Release verification artifacts (attach to the GitHub Release) -------------
$exeName = "LyricsMiniplayer.exe"
$zipName = "$ReleaseName.zip"
$exePath = Join-Path $PSScriptRoot "dist\$exeName"
$sumsPath = Join-Path $PSScriptRoot "dist\SHA256SUMS"
$sbomPath = Join-Path $PSScriptRoot "dist\sbom.cdx.json"
$provenancePath = Join-Path $PSScriptRoot "dist\PROVENANCE.md"

Write-Host "==> Writing SHA256SUMS"
$exeHash = (Get-FileHash -Algorithm SHA256 -Path $exePath).Hash.ToLowerInvariant()
$zipHash = (Get-FileHash -Algorithm SHA256 -Path $zipPath).Hash.ToLowerInvariant()
Write-Utf8NoBomFile -Path $sumsPath -Content "$exeHash  $exeName`n$zipHash  $zipName`n"

Write-Host "==> Generating CycloneDX SBOM"
& $Python -m pip install --quiet "cyclonedx-bom>=4.0.0"
& $Python -m cyclonedx_py requirements requirements.txt --of JSON -o $sbomPath
if ($LASTEXITCODE -ne 0 -or -not (Test-Path $sbomPath)) {
    Write-Error "CycloneDX SBOM generation failed."
}

Write-Host "==> Writing PROVENANCE.md"
$pyVersion = & $Python -c "import sys; print(sys.version.split()[0])"
$lockHash = (Get-FileHash -Algorithm SHA256 -Path (Join-Path $PSScriptRoot "requirements.txt")).Hash.ToLowerInvariant()
$osName = [System.Environment]::OSVersion.VersionString
$arch = $env:PROCESSOR_ARCHITECTURE
$buildCommand = "powershell -ExecutionPolicy Bypass -File .\build.ps1"

$provenance = @"
# Build provenance - LyricsMiniplayer v$Version

This file describes how the accompanying Windows binary was produced.
It is generated by build.ps1 at release time.

## Environment

| Field | Value |
|-------|-------|
| Python | $pyVersion |
| Host OS | $osName |
| Architecture | $arch |
| Lockfile | requirements.txt (pip --require-hashes) |
| Lockfile SHA-256 | $lockHash |

## Exact build command

    $buildCommand

The script installs dependencies from the hashed lockfile, runs PyInstaller
(windowed onefile), packs $zipName, then emits SHA256SUMS,
sbom.cdx.json (CycloneDX JSON), and this provenance file under dist\.

## Verifying downloads

1. Download $zipName (or $exeName) and SHA256SUMS from the same GitHub Release.
2. Confirm the SHA-256 of the file matches the line in SHA256SUMS.
3. Optionally review sbom.cdx.json for the dependency inventory used at build time.

This project does not Authenticode-sign the executable. Integrity is established
via published checksums, the SBOM, and this build recipe - not a paid publisher certificate.
"@

Write-Utf8NoBomFile -Path $provenancePath -Content $provenance

Write-Host "Built: dist\$exeName"
Write-Host "Zip:   dist\$zipName"
Write-Host "Sums:  dist\SHA256SUMS"
Write-Host "SBOM:  dist\sbom.cdx.json"
Write-Host "Prov:  dist\PROVENANCE.md"
Write-Host ""
Write-Host "Attach to the GitHub Release: $zipName, SHA256SUMS, sbom.cdx.json, PROVENANCE.md"
